---
# tasks file for php

    - name: Installation install software-properties-common
      apt: name=software-properties-common

    - name: "Repo PHP 7.4"
      apt_repository:
        repo="ppa:ondrej/php"

    - name: "Updating the repo"
      apt: update_cache=no

   
    - name: Installation PHP 7.4
      apt: name=php7.4 state=present

    - name: install lamp stack packages
      apt:
        pkg: "{{ packages }}"
        state: present
        update_cache: no

